groups: 
- name: example
  rules:
  - alert: BlackboxProbeHttpFailure
    expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
      description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: BlackboxProbeSlowHttp
    expr: avg_over_time(probe_http_duration_seconds[1m]) > 5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: Blackbox probe slow HTTP (instance {{ $labels.instance }})
      description: "HTTP request took more than 5s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: ServerRestarted
    expr: node_time_seconds - node_boot_time_seconds < 60
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Server rstarted (instance {{ $labels.instance }})
      description: "Server has been restarted\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
